language: ruby
rvm:
  - 2.6.4

before_install:
  - chmod +x ./scripts/build.sh

script: ./scripts/build.sh

after_success: true

deploy:
  provider: surge
  project: ./_site
  domain: xanzhu.com
  skip_cleanup: true


branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: 
  bundler 
   directories:
     - /home/travis/.rvm/

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false