language: ruby
rvm:
  - 2.6.2

before_script:
 - chmod +x ./script/build

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/build

deploy:
  provider: surge
  project: ./_site
  domain: xanzhu.com
  

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false