url: "https://xanzhu.com"
baseurl: "" 
title: "xanzhu"

exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - .jekyll-cache
  - .sass-cache
  - _site
  - CNAME
  - package.json
  - package-lock.json