url: "https://xanzhu.com"
baseurl: "" 
title: "xanzhu"

exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - _site
  - CNAME
  - package.json
  - package-lock.json
  - scripts

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-sitemap

# Let users know whats happening site wide. 
code: 503